### ISSUE TITLE
method_condmean(type = "bootstrap", n_samples = 0) returns final pvalue equal to 2

### ISSUE THREAD

**Issue by nociale** [insightsengineering/rbmi#210]
Need to double check validity / testing of two-sided pvalue calculation. In case of `n_samples <= 1` the pvalue should be `NA` for `type = normal`.

EDIT: the default bootstrap method to make inference is `percentile`, and not `normal`. This bug is only related to `percentile`, while `normal` correctly returns `NA`. 

@wolbersm, @gowerc  The formula to compute the p-value in the percentile bootstrap is actually correctly applied: one sided is `((#theta < 0) + 1)/(B+1)`. The two-sided p-value is twice the minimum of the two one-sided p-values. However if `B = 0` the formula will always return a p-value of 2. 
Question: is there a minimum number of bootstrap samples needed to ensure that both p-value and CIs are correctly computed? I think that `B >= 1` will ensure that p-value is always in `[0,1]`.  The estimation of the CIs will also require at least one value (in such case the estimated CIs will just be that value). So, I would make `CIs = c(NA,NA)` only if `B=0`.

**Comment by wolbersm** [comment]
Thanks, it sounds reasonable to me to make CIs = c(NA,NA) only if B=0. (Obviously, very low B's usually don't make much sense but I don't think we should prohibit them.)
I think the issue for B=0 occurs because of the +1 in formula which I took from the Davison book and am sure is useful for larger B.
