### ISSUE TITLE
Installing rbmi does not build vignettes

### ISSUE THREAD

**Issue by nociale** [insightsengineering/rbmi#213]
@gowerc I had to call `devtools::install_github("insightsengineering/rbmi", build_vignettes = TRUE)` in order to be able to visualize the vignette. By calling `devtools::install_github("insightsengineering/rbmi")` the output of `vignette(topic= "quickstart", package = "rbmi")` was just a warning message saying that there are no vignettes called quickstart in rbmi package.

**Comment by gowerc** [comment]
I think this is just standard behaviour of `install_github` as the `build_vignettes` argument is defaulted to FALSE in order to reduce run times.   A more interesting check would be to build the the  tar.gz file  via `devtools::install()` and then install the tar.gz via `install.packages()`  from which the vignette should be built.

**Comment by nociale** [comment]
@gowerc ok. Should we change the readme file from `devtools::install_github("insightsengineering/rbmi")` to `devtools::install_github("insightsengineering/rbmi", build_vignettes = TRUE)` or what?

**Comment by gowerc** [comment]
Potentially... I don't think it really matters either way as it will be changed to `install.packages()` once its on CRAN and I don't expect anyone really to pull it from GitHub. I don't mind either way :)

**Comment by nociale** [comment]
True, I agree. I will change the readme file for the moment since in the readme file it is described how to install the package through github. As you say once in CRAN this will not be needed anymore.
