### ISSUE TITLE
bmlmi print method shows invalid n_samples

### ISSUE THREAD

**Issue by gowerc** [insightsengineering/rbmi#299]
```
  Draws Object
  ------------
  Number of Samples: 6
  Number of Failed Samples: 0
  Model Formula: outcome ~ 1 + group + visit + age + sex + visit * group
  Imputation Type: random
  Method:
      covariance: cs
      threshold: 0.05
      same_cov: TRUE
      REML: TRUE
      B: 6
      D: 4
      n_samples: NULL    <------------
```

This shouldn't be there

**Comment by gowerc** [comment]
@nociale ,  

Looks like we actually hard coded this into the print method:

```
    method <- x$method
    method$n_samples <- ife(
        is.null(method$n_samples),
        "NULL",
        method$n_samples
    )
```

Any idea why? My initial thoughts were this shouldn't be there but am now second guessing myself ...

**Comment by nociale** [comment]
Yes, `n_samples` is not a parameter (or should not be a paramter) of `bmlmi`, since we have `B` and `D`. 

Since `B` is actually the number of samples used in `draws`, do you think it is better to use `n_samples`, instead of `B`?

In any case, one of the two parameters is useless for `bmlmi` (currently `n_samples` is not used).

**Comment by gowerc** [comment]
Did we do this for jackknife to be explicit that nothing is being set ?  I'm just confused as to why we would have added this in the first place...
