### ISSUE TITLE
rbmi 1.3.1 fails on CRAN Fedora GCC machines

### ISSUE THREAD

**Issue by gowerc** [insightsengineering/rbmi#467]
https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/rbmi-00check.html

```
  ── Error ('test-mcmc.R:108:13'): Verbose suppression works ─────────────────────
  Error in `fit_mcmc(designmat = model_df_scaled[, -1, drop = FALSE], outcome = model_df_scaled[, 
      1, drop = TRUE], group = data2[[vars$group]], visit = data2[[vars$visit]], 
      subjid = data2[[vars$subjid]], method = method, quiet = quiet)`: unable to load shared object '/tmp/RtmpG4gemS/working_dir/Rtmp0GLnEK/file1d3c0462d5d0ba.so':
    libunwind.so.1: cannot open shared object file: No such file or directory
```

**Comment by luwidmer** [comment]
@gowerc the clang one is also interesting with a very huge vector trying to be allocated? rstan was last tested on a different version of r-devel, so I doubt this is directly comparable. Given the > 100000 Gb vector allocation my speculation would be something to be quite broken up the dependency chain.

**Comment by gravesti** [comment]
@luwidmer The fedora clang check is still from v1.3.0. There were also problems on the two macos machines which also had run time errors from the Stan models. The thinking was there was some change in a dependency, which is why we introduced the hashing for the models to avoid using some older compiled model.
It's hard to see why that might have broken something on fedora-gcc.

**Comment by luwidmer** [comment]
It looks fine now?
